/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yanbal;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Eventos;
import modelo.MisCuentas;
import modelo.MisVentasDAO;

/**
 *
 * @author Bleider
 */
public class MiCuenta extends javax.swing.JFrame {
    
   

    Eventos event = new Eventos();
    MisCuentas mc = new MisCuentas();
    MisVentasDAO misven = new MisVentasDAO();
    
    DecimalFormat formatoDecimal = new DecimalFormat("#,##0.00");

    /**
     * Creates new form MisCuentas
     */
    public MiCuenta() {

        initComponents();
        
        setTitle("Mis Cuentas");
        setIconImage(new ImageIcon(getClass().getResource("/images/miniLogo.png")).getImage());
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.txtMisCuentasModificarPago.setEnabled(false);
        this.txtMisCuentasId.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelMisCuentasMontoVenta = new javax.swing.JLabel();
        labelMisCuentasPagoCampania = new javax.swing.JLabel();
        labelMisCuentasRecaudado = new javax.swing.JLabel();
        labelMisCuentasGananciaTotal = new javax.swing.JLabel();
        cbMisCuentasModificarPago = new javax.swing.JCheckBox();
        txtMisCuentasModificarPago = new javax.swing.JTextField();
        txtMisCuentasId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        jLabel3.setText("Monto De Venta:");

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        jLabel4.setText("Pago Campañal: ");

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        jLabel5.setText("Recaudado:");

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        jLabel6.setText("Ganancia Total:");

        labelMisCuentasMontoVenta.setFont(new java.awt.Font("Rockwell", 1, 15)); // NOI18N
        labelMisCuentasMontoVenta.setText("--------");

        labelMisCuentasPagoCampania.setFont(new java.awt.Font("Rockwell", 1, 15)); // NOI18N
        labelMisCuentasPagoCampania.setText("--------");

        labelMisCuentasRecaudado.setFont(new java.awt.Font("Rockwell", 1, 15)); // NOI18N
        labelMisCuentasRecaudado.setText("--------");

        labelMisCuentasGananciaTotal.setFont(new java.awt.Font("Rockwell", 1, 15)); // NOI18N
        labelMisCuentasGananciaTotal.setText("--------");

        cbMisCuentasModificarPago.setText("Modificar Pago Campañal");
        cbMisCuentasModificarPago.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbMisCuentasModificarPagoStateChanged(evt);
            }
        });
        cbMisCuentasModificarPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbMisCuentasModificarPagoMouseClicked(evt);
            }
        });
        cbMisCuentasModificarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMisCuentasModificarPagoActionPerformed(evt);
            }
        });

        txtMisCuentasModificarPago.setBackground(new java.awt.Color(204, 255, 204));
        txtMisCuentasModificarPago.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 204, 51)));
        txtMisCuentasModificarPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMisCuentasModificarPagoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMisCuentasModificarPagoKeyTyped(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 204, 153));
        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mis Cuentas");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 255, 102)));
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(labelMisCuentasMontoVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(labelMisCuentasRecaudado))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(labelMisCuentasGananciaTotal)))
                        .addGap(79, 79, 79))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbMisCuentasModificarPago)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(labelMisCuentasPagoCampania)))
                        .addGap(18, 18, 18)
                        .addComponent(txtMisCuentasModificarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(txtMisCuentasId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(labelMisCuentasMontoVenta)
                    .addComponent(labelMisCuentasRecaudado))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(labelMisCuentasPagoCampania)
                    .addComponent(labelMisCuentasGananciaTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMisCuentasModificarPago)
                    .addComponent(txtMisCuentasModificarPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMisCuentasId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMisCuentasModificarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMisCuentasModificarPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMisCuentasModificarPagoActionPerformed

    private void cbMisCuentasModificarPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMisCuentasModificarPagoMouseClicked
        // TODO add your handling code h
    }//GEN-LAST:event_cbMisCuentasModificarPagoMouseClicked

    private void cbMisCuentasModificarPagoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbMisCuentasModificarPagoStateChanged
        if (cbMisCuentasModificarPago.isSelected() == true) {
            txtMisCuentasModificarPago.setEnabled(true);
            txtMisCuentasModificarPago.requestFocus();
        } else {
            txtMisCuentasModificarPago.setEnabled(false);
        }
    }//GEN-LAST:event_cbMisCuentasModificarPagoStateChanged

    private void txtMisCuentasModificarPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMisCuentasModificarPagoKeyTyped
        // TODO add your handling code here:
        event.numberDecimalKeyPress(evt, txtMisCuentasModificarPago);
    }//GEN-LAST:event_txtMisCuentasModificarPagoKeyTyped

    private void txtMisCuentasModificarPagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMisCuentasModificarPagoKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String pagoText = txtMisCuentasModificarPago.getText();
            if (!pagoText.isEmpty()) {
                double pagoCamp = Double.parseDouble(pagoText);
                mc.setPagoCampania(pagoCamp);
                misven.ActualizarMisCuentas(mc);
                ActualizarMisCuentas();
                mostrarMisCuentas();
                JOptionPane.showMessageDialog(null, "Actualizado con éxito ");
                txtMisCuentasModificarPago.setText("");
                txtMisCuentasModificarPago.setEnabled(false);
                cbMisCuentasModificarPago.setSelected(false);
            } else {
                JOptionPane.showMessageDialog(null, "Debe digitar un saldo");
            }
        }
    }//GEN-LAST:event_txtMisCuentasModificarPagoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiCuenta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MiCuenta().setVisible(true);
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbMisCuentasModificarPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMisCuentasGananciaTotal;
    private javax.swing.JLabel labelMisCuentasMontoVenta;
    private javax.swing.JLabel labelMisCuentasPagoCampania;
    private javax.swing.JLabel labelMisCuentasRecaudado;
    private javax.swing.JTextField txtMisCuentasId;
    private javax.swing.JTextField txtMisCuentasModificarPago;
    // End of variables declaration//GEN-END:variables

    public void registrarMisCuentas() {

        double montoVenta = misven.MontoVentaMisCuentas();
        double pagoCampanial = misven.PagoCampanialMisCuentas();
        double recaudado = misven.RecaudoMisCuentas();
        double totalGan = montoVenta - pagoCampanial;
        mc.setMontoVenta(montoVenta);
        mc.setPagoCampania(pagoCampanial);
        mc.setRecaudado(recaudado);
        mc.setTotalGanancia(totalGan);
        misven.RegistrarMisCuentas(mc);

    }

    public void mostrarMisCuentas() {
        //double pagoCamp = mc.getPagoCampania();
        int id = misven.idMisCuentas();
        labelMisCuentasPagoCampania.setText("$" +formatoDecimal.format(mc.getPagoCampania()) );
        labelMisCuentasMontoVenta.setText("$" + formatoDecimal.format(mc.getMontoVenta()));
        labelMisCuentasRecaudado.setText("$" + formatoDecimal.format(mc.getRecaudado()));
        labelMisCuentasGananciaTotal.setText("$" + formatoDecimal.format(mc.getTotalGanancia()));
        txtMisCuentasId.setText("" + id);
    }

    public void ActualizarMisCuentas() {
        int id = misven.idMisCuentas();
        double montoVenta = misven.MontoVentaMisCuentas();
        double pagoCampanial = misven.PagoCampanialMisCuentas();
        double recaudado = misven.RecaudoMisCuentas();
        double totalGan = montoVenta - pagoCampanial;

        mc.setMontoVenta(montoVenta);
        mc.setPagoCampania(pagoCampanial);
        mc.setRecaudado(recaudado);
        mc.setTotalGanancia(totalGan);
        mc.setId(id);
        misven.ActualizarMisCuentas(mc);
    }
}
